### ISSUE TITLE
prompt_toolkit: support a recent version

### ISSUE THREAD

**Issue by blshkv** [skelsec/msldap#12]
https://github.com/skelsec/msldap/blob/master/setup.py#L56

The latest version is 3.x. Kindly migrate if it is required

**Comment by blshkv** [comment]
Would be also good not to specify a specific version ```minikerberos==0.2.1```

**Comment by skelsec** [comment]
I'd like to migrate but aiocmd would need to upgrade first, that is the reason this requirement is peresent in my setup.py
As for the kerberos part, that was a typo on my side, will fix it in the next release

**Comment by blshkv** [comment]
I think you should not specify prompt-toolkit requirements because msldap does not call it directly.
However, just because aiocmd a) does not work with version 3 b) does not restrict version 3, this requirement fixes their problem. You should drop it once aiocmd fixed it.

**Comment by blshkv** [comment]
aiocmd is fixed finally, could you please cleanup setup.py and release a new version

**Comment by skelsec** [comment]
this issue has been fixed in the meantime
