### ISSUE TITLE
cd/ls/cat/grep/edit ability

### ISSUE THREAD

**Issue by s0i37** [skelsec/msldap#26]
Hello.
The `msldap` is the only tool which supports pass-the-hash and pass-the-ticket.
But it doesn't support vital functinal such as:
- cd/ls
- performing raw-queries
- pretty print all atributes of some object
- edit attributes with external editor
- delete object
`Shelldap` is a good example of comfortable interface for working with LDAP.

**Comment by skelsec** [comment]
Hello,
`performing raw-queries` can be done with the `query` command  
`delete object` can be done with the `delete_user` command
`pretty print all atributes of some object` this needs some improvements, but the main blocking issue here is that the attribute->pyobj mapping needs to be extended for that, and I have no time.  
`edit attributes with external editor` this is not in scope for the time being.  
`cd/ls` I can add this when time allows

**Comment by s0i37** [comment]
https://github.com/skelsec/msldap/pull/29

**Comment by s0i37** [comment]
Implemented https://github.com/skelsec/msldap/pull/29
