### ISSUE TITLE
CCACHE authentication seems broken

### ISSUE THREAD

**Issue by mubix** [skelsec/msldap#38]
I attempted this:

`msldap ldap+kerberos-ccache://sittingduck.info\uberuser:/tmp/krb5cc_1000@dc01.sittingduck.info`

Resulted in this error:

```
Exception: Kerberos credential must have domain set! ==== UniCredential ====
domain: None
username: None
secret: None
stype: CCACHE
protocol: KERBEROS
```

**Comment by octopwn** [comment]
The issue is that the password field can't contain certain characters hence full file paths for ccache/kirbi/keytab files are not supported. This is a limitation that constantly bugs me

**Comment by mubix** [comment]
So just change directories into the folder (in this case `/tmp/`) and specify krb5cc_1000 there?

**Comment by octopwn** [comment]
yes

**Comment by mubix** [comment]
Worked, sorry should have closed this weeks ago.
