### ISSUE TITLE
Loosen version requirement for ldap3 dependency

### ISSUE THREAD

**Issue by exploide** [skelsec/msldap#7]
I would like to propose loosening the version requirement of the ldap3 dependency.

While I don't know why exactly the old version was required, I assume it is for the same reason impacket and ldapdomaindump had this requirement. Though, for these projects, the latest ldap3 release is compatible again, so the requirement got loosened.

See https://github.com/dirkjanm/ldapdomaindump/issues/19 and https://github.com/SecureAuthCorp/impacket/issues/742

Being compatible with latest ldap3 would be great to avoid packaging conflicts.

**Comment by skelsec** [comment]
Long story short: `ldap3` maintainer likes to change object types returned from API calls between versions without addata/errata anywhere to be found. I do not like to spend hours of my time debugging what has changed in the latest release of a 3rd party lib each time.
If needed I can do some tests if the new version of `ldap3` is behaving nice and can fix that version in the `setup.py` script but I am reluctant to add a loose `ldap3` requirement in my projects ever again.

**Comment by exploide** [comment]
Okay, sad to hear that. Does this happen often? Maybe the maintainers can be convinced to better document breaking changes. At least there already is a [CHANGES.txt](https://github.com/cannatag/ldap3/blob/master/CHANGES.txt).

The problem with pinning old versions is that conflicts can easily arise. For example when I install impacket from git now in a virtualenv and then install something like pypykatz which pulls in msldap, it will fail to install since a newer version of ldap3 is already present. Besides, if a Linux distribution's maintainer ever decides to package your library, it probably will not be possible due to dependency conflicts.

But I understand your concerns and of course this is fully up to you.

Having ldap3 version 2.6.1 tested would be great. If msldap had a small test suite that allows to run it against an existent AD to see if it throws exceptions, I could even help in that by testing it with our lab domain. But I don't know if it is feasible to create such a generic test suite.

**Comment by skelsec** [comment]
I updated the code and now it seems compatible with the new version. Not packaging it to pip just yet, because I'm doing additional testing as well. Let me know if it works for you.

**Comment by exploide** [comment]
Great, thank you! Looks good so far. If I encounter issues, I will let you know.

**Comment by skelsec** [comment]
I guess it can be considered fixed, as you haven't gotten back.
If something is still missing feel free to reopen.
